### ISSUE TITLE
Package removal.

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.node-red#120]
Installed the miio package, node red stopped running because it conflicts with the miio adapter. If I turn off the miio adapter, node red starts. I want to delete the miio node, but I can't do it. not via the pallet Manager, nor via npm uninstall. now the miio node always prevents node red from starting if the miio adapter is running.
```

2020-08-09 18:44:06.436 - debug: node-red.0 (620) Objects client initialize lua scripts
--
2020-08-09 18:44:06.468 - debug: node-red.0 (591) 9 Aug 18:44:06 - [info] Server now running at http://127.0.0.1:1880/
2020-08-09 18:44:06.487 - debug: node-red.0 (620) Objects connected to redis: 0.0.0.0:9001
2020-08-09 18:44:06.491 - debug: node-red.0 (620) objectDB connected
2020-08-09 18:44:06.493 - debug: node-red.0 (620) Redis States: Use Redis connection: redis:6379
2020-08-09 18:44:06.562 - debug: node-red.0 (591) Detected device with identifier 52114272 types Set { 'placeholder', 'miio' } model undefined
2020-08-09 18:44:06.565 - debug: node-red.0 (591) {}
2020-08-09 18:44:06.569 - debug: node-red.0 (591) Detected device with identifier 106103424 types Set { 'placeholder', 'miio' } model undefined
2020-08-09 18:44:06.571 - debug: node-red.0 (591) {}
2020-08-09 18:44:06.582 - debug: node-red.0 (591) 9 Aug 18:44:06 - [info] Starting flows
2020-08-09 18:44:06.977 - debug: node-red.0 (591) 9 Aug 18:44:06 - [info] Started flows
2020-08-09 18:44:07.095 - debug: node-red.0 (591) Detected device with identifier 80841820 types Set { 'placeholder', 'miio' } model undefined
2020-08-09 18:44:07.097 - debug: node-red.0 (591) {}
2020-08-09 18:44:07.113 - debug: node-red.0 (591) Detected device with identifier 292135274 types Set { 'placeholder', 'miio' } model undefined
2020-08-09 18:44:07.115 - debug: node-red.0 (591) {}
2020-08-09 18:44:07.168 - debug: node-red.0 (620) States create User PubSub Client
2020-08-09 18:44:07.274 - debug: node-red.0 (620) States create System PubSub Client
2020-08-09 18:44:07.294 - debug: node-red.0 (591) 9 Aug 18:44:07 - [red] Uncaught Exception:
2020-08-09 18:44:07.297 - debug: node-red.0 (591) 9 Aug 18:44:07 - Error: bind EADDRINUSE 0.0.0.0:9898
at dgram.js:338:20
at processTicksAndRejections (internal/process/task_queues.js:85:21)
2020-08-09 18:44:07.326 - info: node-red.0 (591) node-red exited with 1
2020-08-09 18:44:12.328 - info: node-red.0 (591) Starting node-red: --max-old-space-size=512 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
2020-08-09 18:44:13.387 - debug: node-red.0 (591) 9 Aug 18:44:13 - [info]
Welcome to Node-RED


```

**Comment by Anzic23** [comment]
Perhaps it will be useful for someone. I was able to delete the package with this command:
`npm uninstall node-red-contrib-xiaomi-miio --production --prefix "/opt/iobroker/node_modules/iobroker.node-red" --save`
