### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by Messiahs** [ioBroker/ioBroker.node-red#129]
Error reading field "state" with ioBroker list Node

Log:

```
2020-12-26 18:06:11.112 - info: node-red.0 (5125) starting. Version 2.0.1 in /opt/iobroker/node_modules/iobroker.node-red, node: v12.20.0, js-controller: 3.1.6
--
2020-12-26 18:06:11.801 - info: node-red.0 (5125) Starting node-red: --max-old-space-size=128 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
2020-12-26 18:06:16.713 - warn: node-red.0 (5125) 26 Dec 18:06:16 - [warn] Projekte inaktiviert: editorTheme.projects.enabled=false
2020-12-26 18:11:39.780 - error: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2020-12-26 18:11:39.785 - error: node-red.0 (5140) unhandled promise rejection: Cannot set property '_id' of null
2020-12-26 18:11:39.791 - error: node-red.0 (5140) TypeError: Cannot set property '_id' of null
at /opt/iobroker/node_modules/iobroker.node-red/nodes/ioBroker.js:702:64
at Array.map ()
at /opt/iobroker/node_modules/iobroker.node-red/nodes/ioBroker.js:701:71
at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-12-26 18:11:40.794 - warn: node-red.0 (5140) Terminated (UNCAUGHT_EXCEPTION): Without reason
2020-12-26 18:11:41.322 - info: node-red.0 (5125) node-red exited with 6

```

Field 'state' (field has no value!):
Hue dimmer switch (RWL021)
```
{
  "type": "state",
  "common": {
    "name": "Switch state",
    "type": "boolean",
    "read": true,
    "write": false,
    "role": "switch"
  },
  "native": {},
  "from": "system.adapter.zigbee.0",
  "user": "system.user.admin",
  "ts": 1609016378884,
  "_id": "zigbee.0.00178801xxxxxxxx.state",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

```

ioBroker list Node

```
Topic: zigbee.0.00178801xxxxx.s*
Type: State
As array: Return one array of IDs
Onlay IDs: Return only IDs of object
with values: read state's value and add them to payload
```

If I set field value to true or false the error is gone.

**Comment by Apollon77** [comment]
It seems that you request a state that do not have a value (yet) ...
please install from github and tell me if theissue is fixesd

**Comment by Messiahs** [comment]
> It seems that you request a state that do not have a value (yet) ...
correct...  default value is 'undefined'.

everything is now fine. Thanks !!!
