### ISSUE TITLE
After updating js-controller to 5.02 node-red adapter is stuck in error loop

### ISSUE THREAD

**Issue by Claus1985** [ioBroker/ioBroker.node-red#380]
Since updating js-controller to 5.02 I get the following error from node-red adapter:

`
time | type |  message
-- | -- | --
2023-06-13 17:12:03.052 | error | instance system.adapter.node-red.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
 2023-06-13 17:12:02.392 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
 2023-06-13 17:12:01.881 | error | Parameter "chainedName" needs to be of type "string" but type "undefined" has been passed
 2023-06-13 17:12:01.879 | error | Error: Parameter "chainedName" needs to be of type "string" but type "undefined" has been passed at Validator.assertString (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/validator.js:168:19) at AdapterClass.getCertificates (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:1450:31) at writeSettings (/opt/iobroker/node_modules/iobroker.node-red/main.js:340:17) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.node-red/main.js:566:21) at process.processImmediate (node:internal/timers:478:21)`

How can this be fixed?

Thx and brgds,

Claus

**Comment by m4d-D3v1l** [comment]
The same Error here, please fix it

**Comment by M0dj0** [comment]
Same here

**Comment by m4d-D3v1l** [comment]
Schon jemand eine Lösung gefunden ?

**Comment by Solver23** [comment]
Same Error here. js-controller v5.0.5

**Comment by pepp86** [comment]
It seems to be depending to the certificates. If I disable https, adapter is starting and working.

In this adapter, there is no "chained certificate" choosen in admin dialog compared to e.g. the web adapter.

**Comment by luieiob** [comment]
It works with js-controller 5.0.6.
