### ISSUE TITLE
Cannot start an instance with new version

### ISSUE THREAD

**Issue by manuelheld1** [ioBroker/ioBroker.node-red#474]
when i try to start node-red i got following error
 iobroker debug node-red
Debugger listening on ws://127.0.0.1:9229/55db665c-b56c-498d-9e24-dc3f2f757498
For help, see: https://nodejs.org/en/docs/inspector
/opt/iobroker/node_modules/@mapbox/node-pre-gyp/lib/util/versioning.js:305
    libc: options.target_libc || detect_libc.familySync() || 'unknown',
                                             ^

TypeError: detect_libc.familySync is not a function
    at module.exports.evaluate (/opt/iobroker/node_modules/@mapbox/node-pre-gyp/lib/util/versioning.js:305:46)
    at exports.find (/opt/iobroker/node_modules/@mapbox/node-pre-gyp/lib/pre-binding.js:32:27)
    at Object.<anonymous> (/opt/iobroker/node_modules/bcrypt/bcrypt.js:5:31)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.node-red/main.js:8:16)

Node.js v18.20.2

Anyone an idea whats the issue ?
Thanks

**Comment by Apollon77** [comment]
Da sxheint irgendwas mit deiner lokane npm installation nicht korrekt zu sein. Der Fehler kommt von node-pre-gyp, also an sich einem tool was fpr builing und so genutzt wird und mit nopm mitkommt.

Versuch mal nodejs zu aktualisieren oder so.
