### ISSUE TITLE
node-red-contrib-ccu is not working on ioBroker.node-red

### ISSUE THREAD

**Issue by emeins** [ioBroker/ioBroker.node-red#50]
I am running ioBroker with ioBroker.node-red adapter.
When I install node-red-contrib-ccu the CCU connection is not working. I am not able to select the CCU communication interface, it is greyed out. - https://github.com/HM-RedMatic/RedMatic/issues/141

If I run the node red instance standalone the CCU connection is working well.

Is there any dependency, maybe also an interaction if I also run the CCU adapter on ioBroker in parallel?

**Comment by xast1211** [comment]
Hi emeins,

probiere einmal folgendes...

In der Datei:
/opt/ioBroker/node_modules/iobroker.node-red/settings.js

den logging part hinzufügen:

`// Configure the logging output logging: { // Only console logging is currently supported console: { // Level of logging to be recorded. Options are: // fatal - only those errors which make the application unusable should be recorded // error - record errors which are deemed fatal for a particular request + fatal errors // warn - record problems which are non fatal + errors + fatal errors // info - record information about the general running of the application + warn + error + fatal errors // debug - record information which is more verbose than info + info + warn + error + fatal errors // trace - record very detailed logging + debug + info + warn + error + fatal errors // off - turn off all logging (doesn't affect metrics or audit) level: "info", // Whether or not to include metric events in the log output metrics: false, // Whether or not to include audit events in the log output audit: false } },
`
Siehe Original settings.js von Node-Red.

**Comment by emeins** [comment]
Beim Anlegen des Nodes bekomme ich:

2019-02-03 11:44:54.310 - error: node-red.0 3 Feb 11:44:54 - [error] [ccu-connection:24ebacf1.59c454] TypeError: Cannot convert undefined or null to object
--
at Function.keys ()
at CcuConnectionNode.stats (/opt/iobroker/iobroker-data/node-red/node_modules/node-red-contrib-ccu/nodes/ccu-connection.js:399:42)
at new CcuConnectionNode (/opt/iobroker/iobroker-data/node-red/node_modules/node-red-contrib-ccu/nodes/ccu-connection.js:350:18)
at createNode (/opt/iobroker/node_modules/node-red/red/runtime/nodes/flows/Flow.js:305:18)
at Flow.start (/opt/iobroker/node_modules/node-red/red/runtime/nodes/flows/Flow.js:67:31)
at start (/opt/iobroker/node_modules/node-red/red/runtime/nodes/flows/index.js:328:29)
at /opt/iobroker/node_modules/node-red/red/runtime/nodes/flows/index.js:164:25
at
at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by emeins** [comment]
Beim Neustart des NodeRed Adapters schreibt er folgendes ins Log:

undefined2019-02-03 11:50:00.113 - info: host.raspberrypi object change system.adapter.node-red.0
--
2019-02-03 11:50:00.113 - info: host.raspberrypi stopInstance system.adapter.node-red.0
2019-02-03 11:50:00.121 - info: node-red.0 kill node-red task
2019-02-03 11:50:00.658 - info: node-red.0 node-red exited with 0
2019-02-03 11:50:01.115 - info: host.raspberrypi stopInstance timeout "1000 system.adapter.node-red.0 killing pid 31051
2019-02-03 11:50:01.143 - info: host.raspberrypi instance system.adapter.node-red.0 terminated with code 0 (OK)
2019-02-03 11:50:03.631 - info: host.raspberrypi instance system.adapter.node-red.0 started with pid 31100
2019-02-03 11:50:04.819 - info: node-red.0 starting. Version 1.7.1 in /opt/iobroker/node_modules/iobroker.node-red, node: v8.14.0
2019-02-03 11:50:05.824 - info: node-red.0 Starting node-red: --max-old-space-size=128 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
2019-02-03 11:50:16.367 - warn: node-red.0 3 Feb 11:50:16 - [warn] Projects disabled : set editorTheme.projects.enabled=true to enable
2019-02-03 11:50:52.667 - info: node-red.0 Save /opt/iobroker/iobroker-data/node-red/flows.json
2019-02-03 11:50:54.892 - error: node-red.0 3 Feb 11:50:54 - [error] [ccu-connection:36a84a43.XXXXXX] TypeError: Cannot convert undefined or null to object
at Function.keys ()
at CcuConnectionNode.stats (/opt/iobroker/iobroker-data/node-red/node_modules/node-red-contrib-ccu/nodes/ccu-connection.js:399:42)
at new CcuConnectionNode (/opt/iobroker/iobroker-data/node-red/node_modules/node-red-contrib-ccu/nodes/ccu-connection.js:350:18)
at createNode (/opt/iobroker/node_modules/node-red/red/runtime/nodes/flows/Flow.js:305:18)
at Flow.start (/opt/iobroker/node_modules/node-red/red/runtime/nodes/flows/Flow.js:67:31)
at start (/opt/iobroker/node_modules/node-red/red/runtime/nodes/flows/index.js:328:29)
at /opt/iobroker/node_modules/node-red/red/runtime/nodes/flows/index.js:164:25
at
at process._tickCallback (internal/process/next_tick.js:189:7)
2019-02-03 11:51:09.921 - info: node-red.0 Save /opt/iobroker/iobroker-data/node-red/flows.json
2019-02-03 11:51:11.533 - error: node-red.0 3 Feb 11:51:11 - [error] [ccu-connection:36a84a43.XXXXXX] TypeError: Cannot convert undefined or null to object
at Function.keys ()
at CcuConnectionNode.stats (/opt/iobroker/iobroker-data/node-red/node_modules/node-red-contrib-ccu/nodes/ccu-connection.js:399:42)
at new CcuConnectionNode (/opt/iobroker/iobroker-data/node-red/node_modules/node-red-contrib-ccu/nodes/ccu-connection.js:350:18)
at createNode (/opt/iobroker/node_modules/node-red/red/runtime/nodes/flows/Flow.js:305:18)
at Flow.start (/opt/iobroker/node_modules/node-red/red/runtime/nodes/flows/Flow.js:67:31)
at start (/opt/iobroker/node_modules/node-red/red/runtime/nodes/flows/index.js:328:29)
at /opt/iobroker/node_modules/node-red/red/runtime/nodes/flows/index.js:164:25
at
at process._tickCallback (internal/process/next_tick.js:189:7)
2019-02-03 11:51:12.102 - info: node-red.0 node-red exited with 1
2019-02-03 11:51:17.108 - info: node-red.0 Starting node-red: --max-old-space-size=128 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
2019-02-03 11:51:24.511 - info: host.raspberrypi object change system.adapter.node-red.0
2019-02-03 11:51:24.511 - info: host.raspberrypi stopInstance system.adapter.node-red.0
2019-02-03 11:51:24.520 - info: node-red.0 kill node-red task
2019-02-03 11:51:25.514 - info: host.raspberrypi stopInstance timeout "1000 system.adapter.node-red.0 killing pid 31100
2019-02-03 11:51:25.550 - info: host.raspberrypi instance system.adapter.node-red.0 terminated with code 0 (OK)
2019-02-03 11:51:28.036 - info: host.raspberrypi instance system.adapter.node-red.0 started with pid 31159
2019-02-03 11:51:29.287 - info: node-red.0 starting. Version 1.7.1 in /opt/iobroker/node_modules/iobroker.node-red, node: v8.14.0
2019-02-03 11:51:30.386 - info: node-red.0 Starting node-red: --max-old-space-size=128 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
2019-02-03 11:51:40.603 - warn: node-red.0 3 Feb 11:51:40 - [warn] Projects disabled : set editorTheme.projects.enabled=true to enable
2019-02-03 11:51:43.451 - error: node-red.0 3 Feb 11:51:43 - [error] [ccu-connection:36a84a43._XXXXXX_] TypeError: Cannot convert undefined or null to object
at Function.keys ()
at CcuConnectionNode.stats (/opt/iobroker/iobroker-data/node-red/node_modules/node-red-contrib-ccu/nodes/ccu-connection.js:399:42)
at new CcuConnectionNode (/opt/iobroker/iobroker-data/node-red/node_modules/node-red-contrib-ccu/nodes/ccu-connection.js:350:18)
at createNode (/opt/iobroker/node_modules/node-red/red/runtime/nodes/flows/Flow.js:305:18)
at Flow.start (/opt/iobroker/node_modules/node-red/red/runtime/nodes/flows/Flow.js:67:31)
at start (/opt/iobroker/node_modules/node-red/red/runtime/nodes/flows/index.js:328:29)
at tryCatchReject (/opt/iobroker/node_modules/when/lib/makePromise.js:845:30)
at runContinuation1 (/opt/iobroker/node_modules/when/lib/makePromise.js:804:4)
at Fulfilled.when (/opt/iobroker/node_modules/when/lib/makePromise.js:592:4)
at Pending.run (/opt/iobroker/node_modules/when/lib/makePromise.js:483:13)
at Scheduler._drain (/opt/iobroker/node_modules/when/lib/Scheduler.js:62:19)
at Scheduler.drain (/opt/iobroker/node_modules/when/lib/Scheduler.js:27:9)
at _combinedTickCallback (internal/process/next_tick.js:132:7)
at process._tickCallback (internal/process/next_tick.js:181:9)

**Comment by Apollon77** [comment]
Na dann mach ein bug bei dem node-red-node auf. Iobroker kann da nichts für

**Comment by emeins** [comment]
Erst mal Danke für die Hilfe.
Was mich wundert, wenn ich Node Red standalone installiere, läuft die CCU Connection ohne Probleme, nur halt nicht wenn Node Red als ioBroker Adapter läuft.

**Comment by Apollon77** [comment]
Hast Du mal das Logging aktiviert wie es oben vorgeschlagen ist ? Weil das ist die Ursache. 

Das node geht davon aus das "logging" in der Konfig drin ist.

Duplicate #43

**Comment by emeins** [comment]
Volltreffer! Ich habe folgende Einstellung in **/opt/ioBroker/node_modules/iobroker.node-red/settings.js** ergänzt:

// Configure the logging output
    logging: {
    // Console logging
    console: {
        level: "info",
        metrics: false,
        audit: false
       }
    }

Jetzt läuft es. Danke noch mal.
